# Generated by Django 4.1.2 on 2022-10-10 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('phone', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('paid_status', models.BooleanField(default=False, verbose_name='has purchased a package')),
                ('running_package', models.CharField(choices=[('FREE_TIER', 'free tier'), ('PRO_TIER', 'pro tier'), ('BUSINESS_TIER', 'business tier'), ('ENTERPRISE_TIER', 'enterprise tier')], default='FREE_TIER', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Poll Organizers',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('voter_limit', models.IntegerField(default=10)),
                ('poll_limit', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer')),
            ],
            options={
                'db_table': 'Workspaces',
                'ordering': ['-created_date'],
            },
        ),
    ]
