# Generated by Django 4.1.2 on 2022-10-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_alter_workspace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='image',
            field=models.ImageField(blank=True, upload_to='organizers/'),
        ),
    ]
