# Generated by Django 4.1.2 on 2022-10-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_alter_organizer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organizers/'),
        ),
    ]
