# Generated by Django 4.1.2 on 2022-11-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_alter_organizer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='poll_limit',
            field=models.IntegerField(default=2),
        ),
    ]
