# Generated by Django 4.1.2 on 2022-11-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_alter_workspace_poll_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer'),
        ),
    ]
