# Generated by Django 4.1.2 on 2022-10-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='country',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
