# Generated by Django 4.1.2 on 2022-10-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_alter_voter_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='image',
            field=models.ImageField(blank=True, upload_to='voters/'),
        ),
    ]
