# Generated by Django 4.1.2 on 2022-11-21 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=254)),
                ('intro', models.TextField()),
                ('open', models.BooleanField(default=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.workspace')),
            ],
            options={
                'db_table': 'Polls Table',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='candidates/')),
                ('country', models.CharField(max_length=254)),
                ('bio', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
            options={
                'db_table': 'Poll Candidates',
                'ordering': ['-created_date'],
            },
        ),
    ]
