# Generated by Django 4.1.2 on 2022-10-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to='candidates/'),
        ),
    ]
