# Generated by Django 4.1.2 on 2022-11-21 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voters', '0001_initial'),
        ('ballot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voter'),
        ),
    ]
